# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QThread, pyqtSignal
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

class Ui_MainWindow(QObject):
        # ! new - must rewrite
    finished = pyqtSignal()
    error = pyqtSignal(tuple)
    result = pyqtSignal(object)
    # progress = pyqtSignal(int)
    updateText = pyqtSignal(str)
    # hidebar=pyqtSignal()
    m_error = pyqtSignal()
    estimated = pyqtSignal(str)
    modelpop = pyqtSignal()
    modelsave= pyqtSignal()
    model_success = pyqtSignal()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 710)
        MainWindow.setFixedSize(966, 710)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 971, 691))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setWhatsThis("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(310, 100, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_6)
        self.label_20.setGeometry(QtCore.QRect(430, 170, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_6)
        self.label_21.setGeometry(QtCore.QRect(350, 240, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 440, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.get_started_btn = QtWidgets.QPushButton(self.page_6)
        self.get_started_btn.setGeometry(QtCore.QRect(170, 320, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.get_started_btn.setFont(font)
        self.get_started_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/finish-flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get_started_btn.setIcon(icon1)
        self.get_started_btn.setIconSize(QtCore.QSize(30, 30))
        self.get_started_btn.setCheckable(False)
        self.get_started_btn.setAutoRepeat(False)
        self.get_started_btn.setAutoDefault(False)
        self.get_started_btn.setDefault(True)
        self.get_started_btn.setObjectName("get_started_btn")
        self.history_btn = QtWidgets.QPushButton(self.page_6)
        self.history_btn.setGeometry(QtCore.QRect(170, 380, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.history_btn.setFont(font)
        self.history_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/hst.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_btn.setIcon(icon2)
        self.history_btn.setIconSize(QtCore.QSize(30, 30))
        self.history_btn.setObjectName("history_btn")
        self.label_35 = QtWidgets.QLabel(self.page_6)
        self.label_35.setGeometry(QtCore.QRect(610, 40, 461, 521))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("img/icon.png"))
        self.label_35.setObjectName("label_35")
        self.label_54 = QtWidgets.QLabel(self.page_6)
        self.label_54.setGeometry(QtCore.QRect(-50, -120, 491, 551))
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_6)
        self.label_55.setGeometry(QtCore.QRect(-190, 460, 491, 641))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_55.setObjectName("label_55")
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_35.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.pushButton_3.raise_()
        self.get_started_btn.raise_()
        self.history_btn.raise_()
        self.stackedWidget.addWidget(self.page_6)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.nextButton = QtWidgets.QPushButton(self.page)
        self.nextButton.setGeometry(QtCore.QRect(650, 330, 131, 31))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton.setDefault(True)
        self.nextButton.setObjectName("nextButton")
        self.label_22 = QtWidgets.QLabel(self.page)
        self.label_22.setGeometry(QtCore.QRect(230, 10, 481, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.home_btn2 = QtWidgets.QPushButton(self.page)
        self.home_btn2.setGeometry(QtCore.QRect(160, 330, 121, 31))
        self.home_btn2.setObjectName("home_btn2")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(150, 120, 636, 108))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 10, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 70, 221, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.importButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.importButton.setDefault(True)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_2.addWidget(self.importButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 42, 611, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pathLine = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pathLine.setObjectName("pathLine")
        self.horizontalLayout.addWidget(self.pathLine)
        self.browseButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.browseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(160, 240, 621, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(101, 50, 401, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_btn_c = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_btn_c.setObjectName("radio_btn_c")
        self.gridLayout.addWidget(self.radio_btn_c, 0, 0, 1, 1)
        self.radio_btn_r = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_btn_r.setObjectName("radio_btn_r")
        self.gridLayout.addWidget(self.radio_btn_r, 0, 1, 1, 1)
        self.radio_btn_ts = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_btn_ts.setObjectName("radio_btn_ts")
        self.gridLayout.addWidget(self.radio_btn_ts, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 291, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_45 = QtWidgets.QLabel(self.page)
        self.label_45.setGeometry(QtCore.QRect(-110, 200, 491, 621))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page)
        self.label_46.setGeometry(QtCore.QRect(610, 230, 491, 521))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_46.setObjectName("label_46")
        self.label_46.raise_()
        self.label_45.raise_()
        self.nextButton.raise_()
        self.label_22.raise_()
        self.home_btn2.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.backButton1 = QtWidgets.QPushButton(self.page_2)
        self.backButton1.setGeometry(QtCore.QRect(60, 620, 80, 31))
        self.backButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton1.setObjectName("backButton1")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(170, 10, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.describe_text_edit = QtWidgets.QTextEdit(self.page_2)
        self.describe_text_edit.setGeometry(QtCore.QRect(140, 510, 541, 141))
        self.describe_text_edit.setReadOnly(True)
        self.describe_text_edit.setObjectName("describe_text_edit")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(140, 480, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.nextButton1 = QtWidgets.QPushButton(self.page_2)
        self.nextButton1.setGeometry(QtCore.QRect(790, 620, 80, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nextButton1.setFont(font)
        self.nextButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton1.setDefault(True)
        self.nextButton1.setObjectName("nextButton1")
        self.load_DB_btn = QtWidgets.QPushButton(self.page_2)
        self.load_DB_btn.setGeometry(QtCore.QRect(690, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_DB_btn.setFont(font)
        self.load_DB_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_DB_btn.setObjectName("load_DB_btn")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(140, 120, 541, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(139, 430, 541, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(90, 10, 365, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        self.forecast_box = QtWidgets.QSpinBox(self.layoutWidget3)
        self.forecast_box.setObjectName("forecast_box")
        self.horizontalLayout_17.addWidget(self.forecast_box)
        self.tiny_btn = QtWidgets.QPushButton(self.page_2)
        self.tiny_btn.setGeometry(QtCore.QRect(790, 580, 80, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tiny_btn.setFont(font)
        self.tiny_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tiny_btn.setObjectName("tiny_btn")
        self.label_36 = QtWidgets.QLabel(self.page_2)
        self.label_36.setGeometry(QtCore.QRect(-290, 10, 531, 531))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("img/target.png"))
        self.label_36.setObjectName("label_36")
        self.label_44 = QtWidgets.QLabel(self.page_2)
        self.label_44.setGeometry(QtCore.QRect(700, 20, 491, 511))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_44.setObjectName("label_44")
        self.label_47 = QtWidgets.QLabel(self.page_2)
        self.label_47.setGeometry(QtCore.QRect(700, 440, 491, 561))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_47.setObjectName("label_47")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setGeometry(QtCore.QRect(220, 90, 427, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_37 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_18.addWidget(self.label_37)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("min-width:150px;")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_3)
        self.label_47.raise_()
        self.label_44.raise_()
        self.label_36.raise_()
        self.backButton1.raise_()
        self.label_23.raise_()
        self.describe_text_edit.raise_()
        self.label_13.raise_()
        self.nextButton1.raise_()
        self.load_DB_btn.raise_()
        self.tableWidget.raise_()
        self.frame_4.raise_()
        self.tiny_btn.raise_()
        self.layoutWidget.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.dbTable = QtWidgets.QTableWidget(self.page_5)
        self.dbTable.setGeometry(QtCore.QRect(82, 76, 291, 471))
        self.dbTable.setObjectName("dbTable")
        self.dbTable.setColumnCount(0)
        self.dbTable.setRowCount(0)
        self.back_btn = QtWidgets.QPushButton(self.page_5)
        self.back_btn.setGeometry(QtCore.QRect(80, 560, 80, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.back_btn.setFont(font)
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setObjectName("back_btn")
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setGeometry(QtCore.QRect(380, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_5)
        self.layoutWidget4.setGeometry(QtCore.QRect(387, 81, 531, 471))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget4)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.showen_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.showen_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showen_btn.setObjectName("showen_btn")
        self.verticalLayout_7.addWidget(self.showen_btn)
        self.predict_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.predict_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.predict_btn.setObjectName("predict_btn")
        self.verticalLayout_7.addWidget(self.predict_btn)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.label_43 = QtWidgets.QLabel(self.page_5)
        self.label_43.setGeometry(QtCore.QRect(-80, -150, 491, 551))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_43.setObjectName("label_43")
        self.label_43.raise_()
        self.dbTable.raise_()
        self.back_btn.raise_()
        self.label_24.raise_()
        self.layoutWidget.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(390, 100, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(150, 100, 174, 441))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gausianPro_Box = QtWidgets.QCheckBox(self.groupBox)
        self.gausianPro_Box.setObjectName("gausianPro_Box")
        self.gridLayout_2.addWidget(self.gausianPro_Box, 6, 0, 1, 1)
        self.extratreeBox = QtWidgets.QCheckBox(self.groupBox)
        self.extratreeBox.setObjectName("extratreeBox")
        self.gridLayout_2.addWidget(self.extratreeBox, 4, 0, 1, 1)
        self.rforoestBox = QtWidgets.QCheckBox(self.groupBox)
        self.rforoestBox.setObjectName("rforoestBox")
        self.gridLayout_2.addWidget(self.rforoestBox, 16, 0, 1, 1)
        self.qdaBox = QtWidgets.QCheckBox(self.groupBox)
        self.qdaBox.setObjectName("qdaBox")
        self.gridLayout_2.addWidget(self.qdaBox, 18, 0, 1, 1)
        self.pasagrBox = QtWidgets.QCheckBox(self.groupBox)
        self.pasagrBox.setObjectName("pasagrBox")
        self.gridLayout_2.addWidget(self.pasagrBox, 15, 0, 1, 1)
        self.bernoulliBox = QtWidgets.QCheckBox(self.groupBox)
        self.bernoulliBox.setObjectName("bernoulliBox")
        self.gridLayout_2.addWidget(self.bernoulliBox, 2, 0, 1, 1)
        self.multinbBox = QtWidgets.QCheckBox(self.groupBox)
        self.multinbBox.setObjectName("multinbBox")
        self.gridLayout_2.addWidget(self.multinbBox, 14, 0, 1, 1)
        self.ldaBox = QtWidgets.QCheckBox(self.groupBox)
        self.ldaBox.setObjectName("ldaBox")
        self.gridLayout_2.addWidget(self.ldaBox, 9, 0, 1, 1)
        self.gaussianBox = QtWidgets.QCheckBox(self.groupBox)
        self.gaussianBox.setObjectName("gaussianBox")
        self.gridLayout_2.addWidget(self.gaussianBox, 5, 0, 1, 1)
        self.adaBox = QtWidgets.QCheckBox(self.groupBox)
        self.adaBox.setObjectName("adaBox")
        self.gridLayout_2.addWidget(self.adaBox, 0, 0, 1, 1)
        self.liblinearBox = QtWidgets.QCheckBox(self.groupBox)
        self.liblinearBox.setObjectName("liblinearBox")
        self.gridLayout_2.addWidget(self.liblinearBox, 10, 0, 1, 1)
        self.libsvmBox = QtWidgets.QCheckBox(self.groupBox)
        self.libsvmBox.setObjectName("libsvmBox")
        self.gridLayout_2.addWidget(self.libsvmBox, 12, 0, 1, 1)
        self.knnBox = QtWidgets.QCheckBox(self.groupBox)
        self.knnBox.setObjectName("knnBox")
        self.gridLayout_2.addWidget(self.knnBox, 8, 0, 1, 1)
        self.gradientBox = QtWidgets.QCheckBox(self.groupBox)
        self.gradientBox.setObjectName("gradientBox")
        self.gridLayout_2.addWidget(self.gradientBox, 7, 0, 1, 1)
        self.sgdBox = QtWidgets.QCheckBox(self.groupBox)
        self.sgdBox.setObjectName("sgdBox")
        self.gridLayout_2.addWidget(self.sgdBox, 17, 0, 1, 1)
        self.dtreeBox = QtWidgets.QCheckBox(self.groupBox)
        self.dtreeBox.setObjectName("dtreeBox")
        self.gridLayout_2.addWidget(self.dtreeBox, 3, 0, 1, 1)
        self.linearsvr_Box = QtWidgets.QCheckBox(self.groupBox)
        self.linearsvr_Box.setObjectName("linearsvr_Box")
        self.gridLayout_2.addWidget(self.linearsvr_Box, 11, 0, 1, 1)
        self.ardBox = QtWidgets.QCheckBox(self.groupBox)
        self.ardBox.setObjectName("ardBox")
        self.gridLayout_2.addWidget(self.ardBox, 1, 0, 1, 1)
        self.libsvrBox = QtWidgets.QCheckBox(self.groupBox)
        self.libsvrBox.setObjectName("libsvrBox")
        self.gridLayout_2.addWidget(self.libsvrBox, 13, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setGeometry(QtCore.QRect(190, 10, 481, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.backButton2 = QtWidgets.QPushButton(self.page_3)
        self.backButton2.setGeometry(QtCore.QRect(60, 510, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.backButton2.setFont(font)
        self.backButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton2.setObjectName("backButton2")
        self.layoutWidget5 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(390, 280, 321, 61))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.holdout_box = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.holdout_box.setObjectName("holdout_box")
        self.horizontalLayout_10.addWidget(self.holdout_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.cvfoldsBox = QtWidgets.QSpinBox(self.layoutWidget5)
        self.cvfoldsBox.setObjectName("cvfoldsBox")
        self.horizontalLayout_9.addWidget(self.cvfoldsBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(390, 260, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.layoutWidget6 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(390, 440, 210, 77))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_8.addWidget(self.checkBox_16)
        self.ensembling_checkbox = QtWidgets.QCheckBox(self.layoutWidget6)
        self.ensembling_checkbox.setObjectName("ensembling_checkbox")
        self.verticalLayout_8.addWidget(self.ensembling_checkbox)
        self.metalearning_checkbox = QtWidgets.QCheckBox(self.layoutWidget6)
        self.metalearning_checkbox.setObjectName("metalearning_checkbox")
        self.verticalLayout_8.addWidget(self.metalearning_checkbox)
        self.layoutWidget7 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(390, 150, 321, 26))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.memory_box = QtWidgets.QSpinBox(self.layoutWidget7)
        self.memory_box.setObjectName("memory_box")
        self.horizontalLayout_6.addWidget(self.memory_box)
        self.layoutWidget8 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(390, 180, 321, 25))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.ressampleCombo = QtWidgets.QComboBox(self.layoutWidget8)
        self.ressampleCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ressampleCombo.setObjectName("ressampleCombo")
        self.horizontalLayout_7.addWidget(self.ressampleCombo)
        self.layoutWidget9 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(390, 210, 321, 25))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.metricCombo = QtWidgets.QComboBox(self.layoutWidget9)
        self.metricCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.metricCombo.setObjectName("metricCombo")
        self.horizontalLayout_8.addWidget(self.metricCombo)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(390, 420, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.layoutWidget10 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(390, 350, 321, 25))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        spacerItem4 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.test_sz_box = QtWidgets.QDoubleSpinBox(self.layoutWidget10)
        self.test_sz_box.setObjectName("test_sz_box")
        self.horizontalLayout_11.addWidget(self.test_sz_box)
        self.savemodel_Box = QtWidgets.QCheckBox(self.page_3)
        self.savemodel_Box.setGeometry(QtCore.QRect(390, 530, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.savemodel_Box.setFont(font)
        self.savemodel_Box.setObjectName("savemodel_Box")
        self.run_Button = QtWidgets.QPushButton(self.page_3)
        self.run_Button.setGeometry(QtCore.QRect(390, 570, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.run_Button.setFont(font)
        self.run_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_Button.setStyleSheet("color:rgb(16, 32, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 35px;\n"
"border-color: black;")
        self.run_Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/play_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_Button.setIcon(icon3)
        self.run_Button.setIconSize(QtCore.QSize(65, 65))
        self.run_Button.setDefault(True)
        self.run_Button.setObjectName("run_Button")
        self.nextButton2_2 = QtWidgets.QPushButton(self.page_3)
        self.nextButton2_2.setGeometry(QtCore.QRect(150, 40, 41, 31))
        self.nextButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton2_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton2_2.setIcon(icon4)
        self.nextButton2_2.setIconSize(QtCore.QSize(25, 25))
        self.nextButton2_2.setObjectName("nextButton2_2")
        self.hist_btn = QtWidgets.QPushButton(self.page_3)
        self.hist_btn.setGeometry(QtCore.QRect(670, 40, 41, 31))
        self.hist_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hist_btn.setText("")
        self.hist_btn.setIcon(icon2)
        self.hist_btn.setIconSize(QtCore.QSize(25, 25))
        self.hist_btn.setObjectName("hist_btn")
        self.result_text = QtWidgets.QTextEdit(self.page_3)
        self.result_text.setGeometry(QtCore.QRect(470, 590, 251, 31))
        self.result_text.setReadOnly(True)
        self.result_text.setObjectName("result_text")
        self.layoutWidget11 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget11.setGeometry(QtCore.QRect(390, 120, 308, 25))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.timeLeft_box = QtWidgets.QSpinBox(self.layoutWidget11)
        self.timeLeft_box.setObjectName("timeLeft_box")
        self.horizontalLayout_5.addWidget(self.timeLeft_box)
        self.label_40 = QtWidgets.QLabel(self.page_3)
        self.label_40.setGeometry(QtCore.QRect(620, 380, 271, 271))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("img/setting.png"))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.page_3)
        self.label_41.setGeometry(QtCore.QRect(721, -200, 491, 591))
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.page_3)
        self.label_42.setGeometry(QtCore.QRect(-120, 440, 491, 531))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_42.setObjectName("label_42")
        self.label_42.raise_()
        self.label_41.raise_()
        self.label_40.raise_()
        self.label_15.raise_()
        self.groupBox.raise_()
        self.label_25.raise_()
        self.backButton2.raise_()
        self.layoutWidget.raise_()
        self.label_16.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_6.raise_()
        self.layoutWidget.raise_()
        self.savemodel_Box.raise_()
        self.run_Button.raise_()
        self.nextButton2_2.raise_()
        self.hist_btn.raise_()
        self.result_text.raise_()
        self.layoutWidget.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tabWidget = QtWidgets.QTabWidget(self.page_4)
        self.tabWidget.setGeometry(QtCore.QRect(60, 110, 311, 471))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.classification_table = QtWidgets.QTableWidget(self.tab)
        self.classification_table.setObjectName("classification_table")
        self.classification_table.setColumnCount(0)
        self.classification_table.setRowCount(0)
        self.gridLayout_4.addWidget(self.classification_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.regression_table = QtWidgets.QTableWidget(self.tab_2)
        self.regression_table.setGeometry(QtCore.QRect(10, 10, 431, 421))
        self.regression_table.setObjectName("regression_table")
        self.regression_table.setColumnCount(0)
        self.regression_table.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setGeometry(QtCore.QRect(290, 10, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.home_btn = QtWidgets.QPushButton(self.page_4)
        self.home_btn.setGeometry(QtCore.QRect(220, 40, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.home_btn.setFont(font)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setText("")
        self.home_btn.setIcon(icon4)
        self.home_btn.setIconSize(QtCore.QSize(25, 25))
        self.home_btn.setObjectName("home_btn")
        self.layoutWidget12 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget12.setGeometry(QtCore.QRect(380, 110, 541, 471))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget12)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.show_more_btn = QtWidgets.QPushButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_more_btn.setFont(font)
        self.show_more_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_more_btn.setObjectName("show_more_btn")
        self.verticalLayout_10.addWidget(self.show_more_btn)
        self.stackedWidget.addWidget(self.page_4)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_75 = QtWidgets.QLabel(self.page_11)
        self.label_75.setGeometry(QtCore.QRect(300, 10, 401, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.page_11)
        self.label_76.setGeometry(QtCore.QRect(420, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.ok_btn_3 = QtWidgets.QPushButton(self.page_11)
        self.ok_btn_3.setGeometry(QtCore.QRect(450, 620, 80, 23))
        self.ok_btn_3.setObjectName("ok_btn_3")
        self.weights_table = QtWidgets.QTableWidget(self.page_11)
        self.weights_table.setGeometry(QtCore.QRect(40, 140, 901, 471))
        self.weights_table.setObjectName("weights_table")
        self.weights_table.setColumnCount(0)
        self.weights_table.setRowCount(0)
        self.label_49 = QtWidgets.QLabel(self.page_11)
        self.label_49.setGeometry(QtCore.QRect(680, -180, 491, 501))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_49.setObjectName("label_49")
        self.label_49.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.ok_btn_3.raise_()
        self.weights_table.raise_()
        self.stackedWidget.addWidget(self.page_11)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.home_btn2_2 = QtWidgets.QPushButton(self.page_7)
        self.home_btn2_2.setGeometry(QtCore.QRect(10, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.home_btn2_2.setFont(font)
        self.home_btn2_2.setText("")
        self.home_btn2_2.setIcon(icon4)
        self.home_btn2_2.setIconSize(QtCore.QSize(25, 25))
        self.home_btn2_2.setObjectName("home_btn2_2")
        self.label_28 = QtWidgets.QLabel(self.page_7)
        self.label_28.setGeometry(QtCore.QRect(390, 0, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_34 = QtWidgets.QLabel(self.page_7)
        self.label_34.setGeometry(QtCore.QRect(260, 180, 451, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_8)
        self.layoutWidget_2.setGeometry(QtCore.QRect(670, 590, 171, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.back_btn_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.back_btn_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_7.setObjectName("back_btn_7")
        self.horizontalLayout_12.addWidget(self.back_btn_7)
        self.next_btn_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.next_btn_7.setObjectName("next_btn_7")
        self.horizontalLayout_12.addWidget(self.next_btn_7)
        self.extract_frame = QtWidgets.QFrame(self.page_8)
        self.extract_frame.setGeometry(QtCore.QRect(80, 260, 751, 311))
        self.extract_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extract_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extract_frame.setObjectName("extract_frame")
        self.label_31 = QtWidgets.QLabel(self.extract_frame)
        self.label_31.setGeometry(QtCore.QRect(120, 10, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.custom_radio = QtWidgets.QRadioButton(self.extract_frame)
        self.custom_radio.setGeometry(QtCore.QRect(40, 60, 211, 21))
        self.custom_radio.setObjectName("custom_radio")
        self.text_settings = QtWidgets.QTextEdit(self.extract_frame)
        self.text_settings.setGeometry(QtCore.QRect(40, 80, 271, 191))
        self.text_settings.setObjectName("text_settings")
        self.extract_btn = QtWidgets.QPushButton(self.extract_frame)
        self.extract_btn.setGeometry(QtCore.QRect(540, 250, 171, 41))
        self.extract_btn.setObjectName("extract_btn")
        self.submit_btn = QtWidgets.QPushButton(self.extract_frame)
        self.submit_btn.setGeometry(QtCore.QRect(230, 270, 81, 23))
        self.submit_btn.setObjectName("submit_btn")
        self.comprehensive_radio = QtWidgets.QRadioButton(self.extract_frame)
        self.comprehensive_radio.setGeometry(QtCore.QRect(341, 87, 211, 20))
        self.comprehensive_radio.setObjectName("comprehensive_radio")
        self.minimal_radio = QtWidgets.QRadioButton(self.extract_frame)
        self.minimal_radio.setGeometry(QtCore.QRect(341, 119, 181, 20))
        self.minimal_radio.setObjectName("minimal_radio")
        self.efficient_radio = QtWidgets.QRadioButton(self.extract_frame)
        self.efficient_radio.setGeometry(QtCore.QRect(341, 151, 211, 20))
        self.efficient_radio.setObjectName("efficient_radio")
        self.roll_frame = QtWidgets.QFrame(self.page_8)
        self.roll_frame.setGeometry(QtCore.QRect(70, 20, 751, 201))
        self.roll_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roll_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roll_frame.setObjectName("roll_frame")
        self.label1234 = QtWidgets.QLabel(self.roll_frame)
        self.label1234.setGeometry(QtCore.QRect(180, 0, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label1234.setFont(font)
        self.label1234.setObjectName("label1234")
        self.roll_btn = QtWidgets.QPushButton(self.roll_frame)
        self.roll_btn.setGeometry(QtCore.QRect(550, 140, 171, 41))
        self.roll_btn.setObjectName("roll_btn")
        self.layoutWidget13 = QtWidgets.QWidget(self.roll_frame)
        self.layoutWidget13.setGeometry(QtCore.QRect(110, 60, 341, 121))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.sort_box = QtWidgets.QComboBox(self.layoutWidget13)
        self.sort_box.setMaximumSize(QtCore.QSize(79, 16777215))
        self.sort_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sort_box.setStyleSheet("selection-background-color:#2E8BC0;")
        
        self.sort_box.setObjectName("sort_box")
        self.horizontalLayout_4.addWidget(self.sort_box)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.min_timeshift_box = QtWidgets.QSpinBox(self.layoutWidget13)
        self.min_timeshift_box.setObjectName("min_timeshift_box")
        self.horizontalLayout_14.addWidget(self.min_timeshift_box)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.max_timeshift_box = QtWidgets.QSpinBox(self.layoutWidget13)
        self.max_timeshift_box.setObjectName("max_timeshift_box")
        self.horizontalLayout_15.addWidget(self.max_timeshift_box)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget13)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_16.addWidget(self.checkBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.label_51 = QtWidgets.QLabel(self.page_8)
        self.label_51.setGeometry(QtCore.QRect(800, 30, 461, 531))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_51.setObjectName("label_51")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_30 = QtWidgets.QLabel(self.page_9)
        self.label_30.setGeometry(QtCore.QRect(350, -10, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.frame_3 = QtWidgets.QFrame(self.page_9)
        self.frame_3.setGeometry(QtCore.QRect(80, 530, 511, 81))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(60, 50, 401, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.reg_radio_btn = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.reg_radio_btn.setObjectName("reg_radio_btn")
        self.gridLayout_3.addWidget(self.reg_radio_btn, 0, 1, 1, 1)
        self.cl_radio_btn = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.cl_radio_btn.setObjectName("cl_radio_btn")
        self.gridLayout_3.addWidget(self.cl_radio_btn, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(120, 10, 291, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.layoutWidget14 = QtWidgets.QWidget(self.page_9)
        self.layoutWidget14.setGeometry(QtCore.QRect(80, 80, 511, 411))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget14)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_12.addWidget(self.label_27)
        self.features_preview = QtWidgets.QTableWidget(self.layoutWidget14)
        self.features_preview.setObjectName("features_preview")
        self.features_preview.setColumnCount(0)
        self.features_preview.setRowCount(0)
        self.verticalLayout_12.addWidget(self.features_preview)
        self.layoutWidget15 = QtWidgets.QWidget(self.page_9)
        self.layoutWidget15.setGeometry(QtCore.QRect(660, 80, 141, 411))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget15)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget15)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_13.addWidget(self.label_32)
        self.target_preview = QtWidgets.QTableWidget(self.layoutWidget15)
        self.target_preview.setObjectName("target_preview")
        self.target_preview.setColumnCount(0)
        self.target_preview.setRowCount(0)
        self.verticalLayout_13.addWidget(self.target_preview)
        self.layoutWidget16 = QtWidgets.QWidget(self.page_9)
        self.layoutWidget16.setGeometry(QtCore.QRect(640, 580, 168, 31))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget16)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.back_btn_8 = QtWidgets.QPushButton(self.layoutWidget16)
        self.back_btn_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_8.setObjectName("back_btn_8")
        self.horizontalLayout_13.addWidget(self.back_btn_8)
        self.next_btn_8 = QtWidgets.QPushButton(self.layoutWidget16)
        self.next_btn_8.setDefault(True)
        self.next_btn_8.setObjectName("next_btn_8")
        self.horizontalLayout_13.addWidget(self.next_btn_8)
        self.pushButton = QtWidgets.QPushButton(self.page_9)
        self.pushButton.setGeometry(QtCore.QRect(660, 510, 141, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setObjectName("pushButton")
        # self.label_52 = QtWidgets.QLabel(self.page_9)
        # self.label_52.setGeometry(QtCore.QRect(590, -70, 491, 531))
        # self.label_52.setText("")
        # self.label_52.setPixmap(QtGui.QPixmap("img/circ.png"))
        # self.label_52.setObjectName("label_52")
        # self.label_52.raise_()
        self.label_30.raise_()
        self.frame_3.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton.raise_()
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_39 = QtWidgets.QLabel(self.page_10)
        self.label_39.setGeometry(QtCore.QRect(130, 0, 651, 91))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.frame_export = QtWidgets.QFrame(self.page_10)
        self.frame_export.setGeometry(QtCore.QRect(140, 350, 621, 161))
        self.frame_export.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_export.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_export.setObjectName("frame_export")
        self.label_78 = QtWidgets.QLabel(self.frame_export)
        self.label_78.setGeometry(QtCore.QRect(120, 10, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.export_btn = QtWidgets.QPushButton(self.frame_export)
        self.export_btn.setGeometry(QtCore.QRect(170, 70, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.export_btn.setFont(font)
        self.export_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_btn.setObjectName("export_btn")
        self.frame_pref = QtWidgets.QFrame(self.page_10)
        self.frame_pref.setGeometry(QtCore.QRect(140, 80, 621, 261))
        self.frame_pref.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pref.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pref.setObjectName("frame_pref")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_pref)
        self.layoutWidget_6.setGeometry(QtCore.QRect(130, 90, 321, 25))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_20.addWidget(self.label_38)
        self.split_box = QtWidgets.QDoubleSpinBox(self.layoutWidget_6)
        self.split_box.setObjectName("split_box")
        self.horizontalLayout_20.addWidget(self.split_box)
        self.micro_btn = QtWidgets.QPushButton(self.frame_pref)
        self.micro_btn.setGeometry(QtCore.QRect(160, 130, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.micro_btn.setFont(font)
        self.micro_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.micro_btn.setObjectName("micro_btn")
        self.label_77 = QtWidgets.QLabel(self.frame_pref)
        self.label_77.setGeometry(QtCore.QRect(100, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.home_microbtn = QtWidgets.QPushButton(self.page_10)
        self.home_microbtn.setGeometry(QtCore.QRect(80, 30, 41, 31))
        self.home_microbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_microbtn.setText("")
        self.home_microbtn.setIcon(icon4)
        self.home_microbtn.setIconSize(QtCore.QSize(25, 25))
        self.home_microbtn.setObjectName("home_microbtn")
        self.label_53 = QtWidgets.QLabel(self.page_10)
        self.label_53.setGeometry(QtCore.QRect(740, 240, 491, 581))
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("img/circ.png"))
        self.label_53.setObjectName("label_53")
        self.stackedWidget.addWidget(self.page_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        #must include
        # self.hidebar.connect(self.frame_progress.hide)
        self.m_error.connect(self.model_error)
        self.updateText.connect(self.result_text.setText)
        self.modelpop.connect(self.model_pop)
        self.model_success.connect(self.pop_success)

        self.modelsave.connect(self.model_save)

        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.nextButton.clicked.connect(self.nextSlot)
        self.importButton.clicked.connect(self.importSlot)
        self.timeLeft_box.valueChanged['QString'].connect(self.timeleft_Slot)
        self.comboBox.activated['QString'].connect(self.featureSlot)
        self.browseButton.clicked.connect(self.browseSlot)
        self.cancelButton.clicked.connect(self.cancelSlot)
        self.backButton2.clicked.connect(self.backSlot_1)
        self.memory_box.valueChanged['QString'].connect(self.ensmemory_Slot)
        self.metricCombo.activated['QString'].connect(self.metricBox)
        self.ressampleCombo.activated['QString'].connect(self.resampleBox)
        self.checkBox_16.stateChanged['int'].connect(self.prepro_Checked)
        self.adaBox.stateChanged['int'].connect(self.adaChecked)
        self.groupBox.toggled['bool'].connect(self.select_all_Estimators)
        self.bernoulliBox.stateChanged['int'].connect(self.bernoulliChecked)
        self.dtreeBox.stateChanged['int'].connect(self.dectreeChecked)
        self.extratreeBox.stateChanged['int'].connect(self.extraTreeChecked)
        self.gaussianBox.stateChanged['int'].connect(self.gausianChecked)
        self.gradientBox.stateChanged['int'].connect(self.gradient_checked)
        self.knnBox.stateChanged['int'].connect(self.knnChecked)
        self.ldaBox.stateChanged['int'].connect(self.ldaChecked)
        self.liblinearBox.stateChanged['int'].connect(self.liblinearChecked)
        self.libsvmBox.stateChanged['int'].connect(self.libsvmChecked)
        self.multinbBox.stateChanged['int'].connect(self.multnbChecked)
        self.pasagrBox.stateChanged['int'].connect(self.pasagrChecked)
        self.rforoestBox.stateChanged['int'].connect(self.rforestChecked)
        self.sgdBox.stateChanged['int'].connect(self.sgdChecked)
        self.qdaBox.stateChanged['int'].connect(self.qdaChecked)
        self.cvfoldsBox.valueChanged['QString'].connect(self.cv_Folds)
        self.holdout_box.valueChanged['QString'].connect(self.holdout_Size)
        self.ardBox.stateChanged['int'].connect(self.ard_Checked)
        self.gausianPro_Box.stateChanged['int'].connect(
            self.gausianPro_Checked)
        self.linearsvr_Box.stateChanged['int'].connect(
            self.liblinearsvr_Checked)
        self.libsvrBox.stateChanged['int'].connect(self.libsvr_Checked)
        self.backButton1.clicked.connect(self.backSlot)
        self.nextButton1.clicked.connect(self.nextSlot_1)
        self.load_DB_btn.clicked.connect(self.load_DB)
        self.savemodel_Box.stateChanged['int'].connect(self.save_Checked)
        self.showen_btn.clicked.connect(self.show_ensembles)
        self.predict_btn.clicked.connect(self.predict_y)
        self.pushButton_2.clicked.connect(self.fetch_model_2)
        self.ensembling_checkbox.stateChanged['int'].connect(
            self.ensembling_checked)
        self.metalearning_checkbox.stateChanged['int'].connect(
            self.metalearning_checked)
        self.test_sz_box.valueChanged['QString'].connect(self.test_sz_Slot)
        # self.run_Button.clicked.connect(self.modelSlot)
        self.home_btn.clicked.connect(self.home_slot)
        self.home_btn2.clicked.connect(self.home_slot)
        self.back_btn.clicked.connect(self.models_back)
        self.get_started_btn.clicked.connect(self.get_started)
        self.history_btn.clicked.connect(self.history_tabs)
        self.radio_btn_c.toggled['bool'].connect(self.radio_c)
        self.radio_btn_r.toggled['bool'].connect(self.radio_r)
        self.radio_btn_ts.toggled['bool'].connect(self.radio_ts)
        self.home_btn2_2.clicked.connect(self.home_slot)
        self.nextButton2_2.clicked.connect(self.home_slot)
        self.pushButton_7.clicked.connect(self.fetch_model_2)
        self.hist_btn.clicked.connect(self.history_tabs)
        self.next_btn_7.clicked.connect(self.next_slot_7)
        self.back_btn_7.clicked.connect(self.back_slot_7)
        self.roll_btn.clicked.connect(self.roll_slot)
        self.extract_btn.clicked.connect(self.extract_slot)
        self.back_btn_8.clicked.connect(self.back_slot_8)
        self.next_btn_8.clicked.connect(self.nextSlot_1)
        self.cl_radio_btn.toggled['bool'].connect(self.radio_c)
        self.reg_radio_btn.toggled['bool'].connect(self.radio_r)
        self.min_timeshift_box.valueChanged['QString'].connect(
            self.min_shift_slot)
        self.max_timeshift_box.valueChanged['QString'].connect(
            self.max_shift_slot)
        self.submit_btn.clicked.connect(self.submit_slot)
        self.sort_box.activated['QString'].connect(self.sort_col_slot)
        self.custom_radio.toggled['bool'].connect(self.custom_slot)
        self.efficient_radio.toggled['bool'].connect(self.efficient_slot)
        self.comprehensive_radio.toggled['bool'].connect(
            self.comprehensive_slot)
        self.minimal_radio.toggled['bool'].connect(self.minimal_slot)
        self.show_more_btn.clicked.connect(self.show_more_slot)
        self.pushButton_7.clicked.connect(self.fetch_model_2)
        self.forecast_box.valueChanged['QString'].connect(self.forecasting_slot)
        self.checkBox.stateChanged['int'].connect(self.max_ts_checked)
        self.ok_btn_3.clicked.connect(self.ok_slot)
        self.pushButton_7.clicked.connect(self.fetch_model_2)
        self.run_Button.clicked.connect(self.modelSlot)
        self.forecast_box.valueChanged['QString'].connect(self.forecasting_slot)
        self.export_btn.clicked.connect(self.export_h)
        self.micro_btn.clicked.connect(self.micro_model)
        self.split_box.valueChanged['QString'].connect(self.set_split)
        self.home_microbtn.clicked.connect(self.home_micro)
        self.tiny_btn.clicked.connect(self.tiny_slot)
        self.pushButton.clicked.connect(self.save_pred)
        self.pushButton_3.clicked.connect(self.aboutslot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto-ML Tool for IoT Applications"))
        self.label_19.setText(_translate("MainWindow", "WELCOME "))
        self.label_20.setText(_translate("MainWindow", "TO "))
        self.label_21.setText(_translate("MainWindow", "DALTON"))
        self.pushButton_3.setText(_translate("MainWindow", "About Dalton 1.0"))
        self.get_started_btn.setText(_translate("MainWindow", "Get Started"))
        self.history_btn.setText(_translate("MainWindow", "Browse History"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.label_22.setText(_translate("MainWindow", "IMPORT YOUR DATA"))
        self.home_btn2.setText(_translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "Select your CSV File"))
        self.cancelButton.setText(_translate("MainWindow", "Clear"))
        self.importButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Import your file!</p></body></html>"))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.label_2.setText(_translate("MainWindow", "File Name"))
        self.browseButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse File Manager</p></body></html>"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.radio_btn_c.setText(_translate("MainWindow", "Classification "))
        self.radio_btn_r.setText(_translate("MainWindow", "Regression"))
        self.radio_btn_ts.setText(_translate("MainWindow", "Time-Series"))
        self.label_3.setText(_translate("MainWindow", "Define the Problem Type"))
        self.backButton1.setText(_translate("MainWindow", "Back"))
        self.label_23.setText(_translate("MainWindow", "SELECT YOUR TARGET"))
        self.label_13.setText(_translate("MainWindow", "Summary"))
        self.nextButton1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create ML model sing autosklearn</p></body></html>"))
        self.nextButton1.setText(_translate("MainWindow", "Αuto-ML"))
        self.load_DB_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Predict values using an existing model</p></body></html>"))
        self.load_DB_btn.setText(_translate("MainWindow", "Load Existing Model"))
        self.label_7.setText(_translate("MainWindow", "Step 2. SELECT FORECASTING STEP     "))
        self.tiny_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Extract Model for Microcontrollers</p></body></html>"))
        self.tiny_btn.setText(_translate("MainWindow", "Micro-ML"))
        self.label_37.setText(_translate("MainWindow", "Step 1. "))
        self.label_5.setText(_translate("MainWindow", "SELECT TARGET"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.label_24.setText(_translate("MainWindow", "MODELS"))
        self.pushButton_2.setText(_translate("MainWindow", "Load Model"))
        self.showen_btn.setText(_translate("MainWindow", "Show Ensembles"))
        self.predict_btn.setText(_translate("MainWindow", "Predict Target"))
        self.label_15.setText(_translate("MainWindow", "Other Parameters"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Estimators: "))
        self.gausianPro_Box.setText(_translate("MainWindow", "gaussian_process"))
        self.extratreeBox.setText(_translate("MainWindow", "extra_trees"))
        self.rforoestBox.setText(_translate("MainWindow", "random_forest"))
        self.qdaBox.setText(_translate("MainWindow", "qda"))
        self.pasagrBox.setText(_translate("MainWindow", "passive_aggressive"))
        self.bernoulliBox.setText(_translate("MainWindow", "bernoulli_nb"))
        self.multinbBox.setText(_translate("MainWindow", "multinomial_nb"))
        self.ldaBox.setText(_translate("MainWindow", "lda"))
        self.gaussianBox.setText(_translate("MainWindow", "gaussian_nb"))
        self.adaBox.setText(_translate("MainWindow", "adaboost"))
        self.liblinearBox.setText(_translate("MainWindow", "liblinear_svc"))
        self.libsvmBox.setText(_translate("MainWindow", "libsvm_svc"))
        self.knnBox.setText(_translate("MainWindow", "k_nearest_neighbors"))
        self.gradientBox.setText(_translate("MainWindow", "gradient_boosting"))
        self.sgdBox.setText(_translate("MainWindow", "sgd"))
        self.dtreeBox.setText(_translate("MainWindow", "decision_tree"))
        self.linearsvr_Box.setText(_translate("MainWindow", "liblinear_svr"))
        self.ardBox.setText(_translate("MainWindow", "ard_regression"))
        self.libsvrBox.setText(_translate("MainWindow", "libsvm_svr"))
        self.label_25.setText(_translate("MainWindow", "PARAMETER TUNING"))
        self.backButton2.setText(_translate("MainWindow", "Back"))
        self.label_12.setText(_translate("MainWindow", "Holdout Train Size"))
        self.label_11.setText(_translate("MainWindow", "CV Folds"))
        self.label_16.setText(_translate("MainWindow", "Resampling Arguments"))
        self.checkBox_16.setText(_translate("MainWindow", "Disable Feature Preprocessing"))
        self.ensembling_checkbox.setText(_translate("MainWindow", "Disable Ensembling"))
        self.metalearning_checkbox.setText(_translate("MainWindow", "Enable Meta-learning"))
        self.label_8.setText(_translate("MainWindow", "Ensemble Memory Limit"))
        self.label_9.setText(_translate("MainWindow", "Resampling Strategy"))
        self.label_10.setText(_translate("MainWindow", "Metric"))
        self.label_6.setText(_translate("MainWindow", "Other Preferences"))
        self.label_14.setText(_translate("MainWindow", "Set Test-Size-Split"))
        self.savemodel_Box.setText(_translate("MainWindow", "Save Model after Creation"))
        self.run_Button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:400;\">Start Modeling!</span></p></body></html>"))
        self.nextButton2_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Go to Home Screen</p></body></html>"))
        self.hist_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse Model History</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Time For Task(seconds)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Classification Models"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Regression Models"))
        self.label_26.setText(_translate("MainWindow", "MODEL HISTORY"))
        self.home_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Go to Home Screen</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Show Model Summary"))
        self.show_more_btn.setText(_translate("MainWindow", "Show more..."))
        self.label_75.setText(_translate("MainWindow", "MODEL HISTORY"))
        self.label_76.setText(_translate("MainWindow", "MODEL LIST"))
        self.ok_btn_3.setText(_translate("MainWindow", "Back"))
        self.weights_table.setSortingEnabled(False)
        self.label_28.setText(_translate("MainWindow", "ABOUT"))
        self.label_34.setText(_translate("MainWindow", "Under Construction"))
        self.back_btn_7.setText(_translate("MainWindow", "Back"))
        self.next_btn_7.setText(_translate("MainWindow", "Auto - ML"))
        self.label_31.setText(_translate("MainWindow", "EXTRACT FEATURES"))
        self.custom_radio.setText(_translate("MainWindow", "Custom Settings (Advanced)"))
        self.extract_btn.setText(_translate("MainWindow", "Extract Features"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
        self.comprehensive_radio.setText(_translate("MainWindow", "Comprehensive FC Parameters"))
        self.minimal_radio.setText(_translate("MainWindow", "Minimal FC Parameters"))
        self.efficient_radio.setText(_translate("MainWindow", "Efficient FC Parameters"))
        self.label1234.setText(_translate("MainWindow", "ROLL TIME SERIES"))
        self.roll_btn.setText(_translate("MainWindow", "Roll Time Series"))
        self.label_17.setText(_translate("MainWindow", "Sort by"))
        self.label_18.setText(_translate("MainWindow", "Minimum Timeshift"))
        self.label_29.setText(_translate("MainWindow", "Maximum Timeshift"))
        self.checkBox.setText(_translate("MainWindow", "Set max value of Maximum Timeshift"))
        self.label_30.setText(_translate("MainWindow", "PREVIEW"))
        self.reg_radio_btn.setText(_translate("MainWindow", "Regression"))
        self.cl_radio_btn.setText(_translate("MainWindow", "Classification "))
        self.label_33.setText(_translate("MainWindow", "Define the Problem Type"))
        self.label_27.setText(_translate("MainWindow", "PREDICTORS ( extracted features )"))
        self.label_32.setText(_translate("MainWindow", "TARGET VARIABLE"))
        self.back_btn_8.setText(_translate("MainWindow", "Back"))
        self.next_btn_8.setText(_translate("MainWindow", "Next"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save the extracted predictors dataset in csv format.</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Save Dataset"))
        self.label_39.setText(_translate("MainWindow", "MICRO MACHINE LEARNING"))
        self.label_78.setText(_translate("MainWindow", "EXPORT MODEL AS C CODE"))
        self.export_btn.setWhatsThis(_translate("MainWindow", "gfgdfgdfgdgd"))
        self.export_btn.setText(_translate("MainWindow", "Export Model"))
        self.label_38.setText(_translate("MainWindow", "Set Test Size Split"))
        self.micro_btn.setText(_translate("MainWindow", "Create Model"))
        self.label_77.setText(_translate("MainWindow", "SET PREFERRED PARAMETERS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

